import * as T from 'three';
import {LEVELS,clamp,rng,makeCourse,courseX,courseY,slope,initialRun,canCollect,collides,rating,powerStage} from './logic.js';
import {material,mesh,createProp,starGeometry,glowTexture,labelTexture} from './assets.js';
import {createHero} from './hero.js';
const R=9.2;
function point(s,theta=0,target=new T.Vector3()){const d=slope(s),h=R*Math.sin(theta),n=Math.sqrt(1+d*d);return target.set(courseX(s)+h/n,courseY(s)+R*(1-Math.cos(theta)),-s+h*d/n);}
function radialShape(count=12){const p=new T.Shape();for(let i=0;i<count*2;i++){const a=i*Math.PI/count,r=i%2?.44:.65;i?p.lineTo(Math.sin(a)*r,Math.cos(a)*r):p.moveTo(0,r);}p.closePath();return new T.ExtrudeGeometry(p,{depth:.17,bevelEnabled:true,bevelSegments:2,bevelSize:.03,bevelThickness:.03,steps:1});}
function moonShape(){const p=new T.Shape();p.absarc(0,0,.63,.3,Math.PI*2-.3,false);p.absarc(.27,0,.52,Math.PI*2-.44,.44,true);return new T.ExtrudeGeometry(p,{depth:.18,bevelEnabled:true,bevelSize:.035,bevelThickness:.025,bevelSegments:2,steps:1});}
export class RaceEngine{
 constructor(canvas,settings,audio,events={}){
  this.canvas=canvas;this.settings=settings;this.audio=audio;this.events=events;this.state='menu';this.theta=0;this.targetTheta=0;this.steer=0;this.last=0;this.elapsed=0;this.uiTimer=0;this.trailTimer=0;this.particles=[];this.fx=[];this.preview=false;
  this.renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,settings.quality==='low'?1:settings.quality==='high'?2:1.5));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.15;this.renderer.shadowMap.enabled=settings.quality==='high'||(settings.quality==='auto'&&innerWidth>1000);this.renderer.shadowMap.type=T.PCFSoftShadowMap;
  this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(60,1,.15,340);this.ambient=new T.HemisphereLight(0xd6eeff,0x477963,2.6);this.scene.add(this.ambient);
  this.sun=new T.DirectionalLight(0xffead0,3.4);this.sun.position.set(-12,28,18);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);this.sun.shadow.camera.left=-15;this.sun.shadow.camera.right=15;this.sun.shadow.camera.top=15;this.sun.shadow.camera.bottom=-15;this.sun.shadow.camera.near=.5;this.sun.shadow.camera.far=90;this.sun.shadow.bias=-.0008;this.sun.shadow.normalBias=.04;this.scene.add(this.sun,this.sun.target);const fill=new T.DirectionalLight(0xa6baff,1.3);fill.position.set(10,8,-8);this.scene.add(fill);
  this.sky=mesh(this.scene,new T.SphereGeometry(290,24,16),new T.ShaderMaterial({side:T.BackSide,depthWrite:false,uniforms:{top:{value:new T.Color(0x62b7ee)},bottom:{value:new T.Color(0xe8f4d7)}},vertexShader:'varying vec3 p;void main(){p=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 p;uniform vec3 top;uniform vec3 bottom;void main(){float h=clamp(normalize(p).y*.8+.22,0.,1.);gl_FragColor=vec4(mix(bottom,top,h),1.);}'}));
  this.hero=createHero();this.scene.add(this.hero.root);this.shadow=mesh(this.scene,new T.PlaneGeometry(3.4,3.4),new T.MeshBasicMaterial({map:glowTexture(),color:0x10232c,transparent:true,opacity:.35,depthWrite:false}),[0,.02,0],[1,1,1],[-Math.PI/2,0,0]);this.dummy=new T.Object3D();this.particleMesh=new T.InstancedMesh(new T.OctahedronGeometry(.10),material(0xffffff,{vertexColors:false,emissive:0x92ffbd,emissiveIntensity:.6}),160);this.particleMesh.instanceMatrix.setUsage(T.DynamicDrawUsage);this.particleMesh.frustumCulled=false;this.particleMesh.count=0;this.scene.add(this.particleMesh);
  this.boundResize=()=>this.resize();window.addEventListener('resize',this.boundResize);this.resize();this.loadLevel(0);this.frame=this.frame.bind(this);this.raf=requestAnimationFrame(this.frame);canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.pause();this.events.error?.('The 3D display was interrupted. Reload to return to the adventure.');});
 }
 resize(){const w=this.canvas.clientWidth||innerWidth,h=this.canvas.clientHeight||innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 loadLevel(index){
  if(this.world){this.scene.remove(this.world);const geo=new Set(),mats=new Set();this.world.traverse(o=>{if(o.geometry)geo.add(o.geometry);if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>mats.add(m));});geo.forEach(g=>g.dispose());mats.forEach(m=>{if(m.map)m.map.dispose();m.dispose();});}
  this.levelIndex=index;this.level=LEVELS[index];this.course=makeCourse(this.level);this.run=initialRun(this.level);this.theta=this.targetTheta=0;this.particles=[];this.clearFX();this.world=new T.Group();this.scene.add(this.world);const L=this.level;this.scene.fog=new T.Fog(L.fog,58,index===1?157:200);this.sky.material.uniforms.top.value.setHex(L.sky);this.sky.material.uniforms.bottom.value.setHex(L.fog);this.ambient.color.setHex(index===1?0x8cd5ff:0xd6eeff);this.ambient.intensity=index===1?2.4:2.6;this.sun.color.setHex(index===2?0xffb58a:0xffedd7);this.sun.intensity=index===1?2:3.4;
  this.makeTrack();this.makeScenery();this.makeItems();const floorMat=material(index===0?0x6aa880:index===1?0x152c48:0xb04d50,{roughness:.84});this.floor=mesh(this.world,new T.PlaneGeometry(1200,1200),floorMat,[0,-4,-500],[1,1,1],[-Math.PI/2,0,0]);this.finishRoot=new T.Group();this.finishRoot.add(createProp('arch',index));point(L.length,0,this.finishRoot.position);this.finishRoot.rotation.y=-Math.atan(slope(L.length));mesh(this.finishRoot,new T.PlaneGeometry(5.5,2),new T.MeshBasicMaterial({map:labelTexture('★',undefined,'#fff3b4'),transparent:true,side:T.DoubleSide}),[0,12,0]);this.world.add(this.finishRoot);
 }
 makeTrack(){
  const pos=[],colors=[],idx=[],color=new T.Color(),length=this.level.length+95,rows=Math.ceil(length/4),cols=24;
  for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const s=j*4-32,a=-1.36+i*2.72/cols,b=a+2.72/cols,base=pos.length/3;for(const[ss,th]of[[s,a],[s,b],[s+4,a],[s+4,b]]){const p=point(ss,th);pos.push(p.x,p.y,p.z);}const side=i<4||i>19,k=side?2:((Math.floor(j/4)+Math.floor(i/4))%2);color.setHex(this.level.track[k]);if(j%4===0)color.multiplyScalar(.91);for(let v=0;v<4;v++)colors.push(color.r,color.g,color.b);idx.push(base,base+2,base+1,base+1,base+2,base+3);}
  const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(pos,3));g.setAttribute('color',new T.Float32BufferAttribute(colors,3));g.setIndex(idx);g.computeVertexNormals();const track=mesh(this.world,g,material(0xffffff,{vertexColors:true,roughness:.42,metalness:.10,side:T.DoubleSide}));track.receiveShadow=true;
  for(const theta of[-1.365,1.365]){const pts=[];for(let s=-32;s<length;s+=8)pts.push(point(s,theta));const curve=new T.CatmullRomCurve3(pts);mesh(this.world,new T.TubeGeometry(curve,Math.ceil(length/5),.13,6,false),material(this.level.accent,{emissive:this.level.accent,emissiveIntensity:.35}));}
 }
 makeScenery(){
  const random=rng(this.level.seed+100),len=this.level.length;this.scenery=[];const add=(type,data)=>{const template=createProp(type,this.levelIndex),m=new T.InstancedMesh(template.geometry,template.material,Math.max(1,data.length));m.instanceMatrix.setUsage(T.DynamicDrawUsage);m.frustumCulled=false;m.count=0;this.world.add(m);this.scenery.push({mesh:m,data});};const trees=[],buildings=[],lamps=[],arches=[],rocks=[],mountains=[];
  for(let s=-20;s<len+100;s+=15)for(const side of[-1,1]){trees.push({s,side:side*(12+random()*12),scale:.85+random()*.65,rot:random()*6.28});if(this.levelIndex===1)rocks.push({s,side:side*(24+random()*6),scale:7+random()*4,rot:random()*6.28});}
  for(let s=45;s<len+80;s+=66)for(const side of[-1,1]){buildings.push({s,side:side*(30+random()*15),scale:1+random(),rot:0});lamps.push({s:s+8,side:side*10.3,scale:1,rot:0});}
  for(let s=105;s<len-60;s+=155)arches.push({s,side:0,scale:1,rot:0});if(this.levelIndex===2)for(let s=160;s<len+150;s+=250)mountains.push({s,side:(random()>.5?1:-1)*52,scale:2,rot:random()*2});add(this.levelIndex===1?'crystal':'tree',trees);add('arch',arches);add(this.levelIndex===0?'building':this.levelIndex===1?'crystal':'mountain',this.levelIndex===2?mountains:buildings);if(this.levelIndex===0)add('lamp',lamps);if(this.levelIndex===1)add('rock',rocks);
 }
 makeItems(){
  const i=this.levelIndex,gemGeo=i===2?new T.DodecahedronGeometry(.52,0):new T.OctahedronGeometry(.58,0);if(i===1)gemGeo.scale(.78,1.5,.78);const specialGeo=i===0?starGeometry():i===1?moonShape():radialShape();this.itemMeshes={};const templates={gem:new T.Mesh(gemGeo,material([0x36eb93,0x5de5fb,0xffba6a][i],{metalness:.32,roughness:.18,emissive:[0x17a751,0x179fa4,0xe97035][i],emissiveIntensity:.55})),special:new T.Mesh(specialGeo,material(i===1?0xbba4ff:0xffd46f,{metalness:.5,roughness:.2,emissive:i===1?0x5c36b4:0x805a07,emissiveIntensity:.50})),rock:createProp('rock',i),orb:createProp('orb',i),goo:createProp('goo',i)};
  for(const[kind,template]of Object.entries(templates)){const m=new T.InstancedMesh(template.geometry,template.material,120);m.instanceMatrix.setUsage(T.DynamicDrawUsage);m.frustumCulled=false;m.count=0;m.castShadow=kind==='rock';this.world.add(m);this.itemMeshes[kind]=m;}
  this.pickupGlows=new T.InstancedMesh(new T.PlaneGeometry(2.4,2.4),new T.MeshBasicMaterial({map:glowTexture(),color:i===1?0x84deff:0x9dffb0,transparent:true,opacity:.25,blending:T.AdditiveBlending,depthWrite:false}),120);this.pickupGlows.instanceMatrix.setUsage(T.DynamicDrawUsage);this.pickupGlows.frustumCulled=false;this.pickupGlows.count=0;this.world.add(this.pickupGlows);
 }
 start(index,mode){this.loadLevel(index);this.run=initialRun(this.level,mode);this.state='countdown';this.countdown=3.2;this.prevCount=4;this.steer=0;this.audio.start(index);this.events.hud?.(this.run,this.level);}
 menu(index=this.levelIndex){this.audio.stop();this.state='menu';if(index!==this.levelIndex)this.loadLevel(index);this.run=initialRun(this.level);this.theta=this.targetTheta=0;this.steer=0;}
 capture(type){this.preview=true;this.state='capture';if(type!=='portrait'&&type!=='share'){const i=LEVELS.findIndex(l=>l.id===type);this.loadLevel(Math.max(0,i));this.run.distance=140;this.run.power=[15,55,100][this.levelIndex];this.run.burst=this.levelIndex===2?4:0;this.run.moving=true;this.captureType='level';}else{this.captureType=type;this.run.power=type==='share'?70:0;}}
 steerTo(value){this.steer=clamp(value,-1,1);}
 nudge(dir){if(this.state==='running')this.targetTheta=clamp(this.targetTheta+dir*.40,-1.05,1.05);}
 jump(){if(this.state!=='running'||this.run.jumpTime>0)return;this.run.jumpTime=.001;this.audio.sfx('jump');}
 smash(){const r=this.run;if(this.state!=='running')return;if(r.power<25&&!r.burst){this.events.message?.('Collect gems to unlock SMASH!',true);return;}if(r.smashTimer>0)return;r.smashTimer=5;r.smashAnim=.65;this.clearHazards(32,.75);this.ring(0x7aff9d,9);this.audio.sfx('smash');this.events.message?.('JAMESY SMASH!');}
 clap(){const r=this.run;if(this.state!=='running')return;if(r.power<65&&!r.burst){this.events.message?.('Thunderclap unlocks at 65 power',true);return;}if(r.clapTimer>0)return;r.clapTimer=9;r.clapAnim=.45;this.clearHazards(52,3);this.ring(0xc39aff,15);this.audio.sfx('clap');this.events.message?.('THUNDERCLAP!');}
 clearHazards(range,width){const r=this.run;for(const it of this.course){if(it.done||it.s<r.distance-2||it.s>r.distance+range||Math.abs(it.theta-this.theta)>width||['gem','special'].includes(it.kind))continue;it.done=true;r.smashes++;r.score+=75;this.emit(point(it.s,it.theta),this.level.accent,15);}}
 ring(color,size){if(this.settings.reduced)return;const m=mesh(this.scene,new T.RingGeometry(.8,1,48),new T.MeshBasicMaterial({color,transparent:true,opacity:.8,side:T.DoubleSide,depthWrite:false}),[this.hero.root.position.x,this.hero.root.position.y+.20,this.hero.root.position.z],[1,1,1],[-Math.PI/2,0,0]);this.fx.push({mesh:m,age:0,size});}
 emit(pos,color,count=8){if(this.settings.reduced)return;for(let i=0;i<count&&this.particles.length<160;i++)this.particles.push({pos:pos.clone().add(new T.Vector3(0,.8,0)),vel:new T.Vector3((Math.random()-.5)*6,2+Math.random()*5,(Math.random()-.5)*6),life:.4+Math.random()*.45,max:.9,color});}
 pause(){if(!['running','countdown'].includes(this.state))return;this.beforePause=this.state;this.state='paused';this.audio.stop();this.steer=0;this.events.paused?.();}
 resume(){if(this.state!=='paused')return;this.state=this.beforePause||'running';this.audio.start(this.levelIndex);}
 finish(complete){if(this.state!=='running')return;this.state='finished';this.audio.stop();this.audio.sfx(complete?'finish':'hit');this.steer=0;const result={...this.run,complete,medals:rating(this.run.collected,this.run.total,this.run.hits,complete)};this.events.finish?.(result,this.level);}
 tick(dt){
  const r=this.run;if(this.state==='countdown'){this.countdown-=dt;const n=Math.ceil(this.countdown);if(n!==this.prevCount){this.prevCount=n;this.events.countdown?.(Math.max(0,n));}if(this.countdown<=0){this.state='running';this.events.message?.('Collect • Dodge • Power up!');}}if(this.state!=='running')return;
  const before=powerStage(r.power,r.burst>0);r.time+=dt;r.distance+=this.level.speed*(r.mode==='cozy'?.82:1.10)*(r.burst>0?1.20:1)*dt;this.targetTheta=clamp(this.targetTheta+this.steer*1.4*dt,-1.05,1.05);this.theta=T.MathUtils.damp(this.theta,this.targetTheta,14,dt);for(const k of['invulnerable','smashTimer','clapTimer','smashAnim','clapAnim'])r[k]=Math.max(0,r[k]-dt);
  if(r.jumpTime>0){r.jumpTime+=dt;if(r.jumpTime>=.95){r.jumpTime=0;r.jump=0;}else r.jump=Math.sin(r.jumpTime/.95*Math.PI)*4.15;}if(r.burst>0){r.burst=Math.max(0,r.burst-dt);if(!r.burst){r.power=50;this.events.message?.('Amazing power! Keep collecting.');}}
  for(const it of this.course){if(it.done||it.s<r.distance-3)continue;if(it.s>r.distance+3)break;const pickup=it.kind==='gem'||it.kind==='special';
   if(pickup&&canCollect(this.theta,it.theta,r.jump,it.kind,r.mode,r.power,r.burst>0)){it.done=true;r.collected++;r.combo++;r.maxCombo=Math.max(r.maxCombo,r.combo);const special=it.kind==='special';if(special)r.specials++;else r.gems++;r.score+=(special?100:25)*Math.min(4,1+Math.floor(r.combo/15));r.power=Math.min(100,r.power+(special?8:3));this.audio.sfx(it.kind);this.emit(point(it.s,it.theta),special?0xffd475:this.level.accent,6);if(r.combo%15===0)this.events.message?.(`${Math.min(4,1+Math.floor(r.combo/15))}× HERO COMBO!`);
   }else if(!pickup&&collides(this.theta,it.theta,r.jump,it.kind)){if(r.burst>0||r.smashAnim>0){it.done=true;r.smashes++;r.score+=75;this.emit(point(it.s,it.theta),this.level.accent,12);}else if(!r.invulnerable){it.done=true;r.hits++;r.combo=0;r.invulnerable=2.3;r.power=Math.max(0,r.power-12);if(r.mode==='hero')r.hearts--;this.audio.sfx('hit');this.emit(point(it.s,it.theta),0xd1a8ee,8);this.events.message?.(r.mode==='cozy'?'Keep going, hero!':'Watch out! Jump or smash.');if(r.hearts<=0){this.finish(false);break;}}}
  }
  if(r.power>=100&&!r.burst&&this.state==='running'){r.burst=6.5;r.bursts++;this.ring(0xa2ffb8,12);this.audio.sfx('power');this.events.message?.('SUPER JAMESY!');}const after=powerStage(r.power,r.burst>0);if(after>before&&after===2){this.audio.sfx('power');this.events.message?.('SMASH UNLOCKED!');}if(after>before&&after===3){this.audio.sfx('power');this.events.message?.('THUNDERCLAP + GEM MAGNET!');}if(r.distance>=this.level.length)this.finish(true);
 }
 drawWorld(dt){
  const r=this.run,D=r.distance,menu=this.state==='menu'||(this.state==='capture'&&this.captureType!=='level');if(menu){this.camera.fov=this.captureType==='portrait'?37:43;this.hero.root.position.set(0,courseY(0),0);this.hero.root.rotation.set(0,-.12,0);const portrait=this.captureType==='portrait';this.camera.position.set(portrait?2.5:1.0,portrait?3.3:3.8,portrait?7.2:10.5);this.camera.lookAt(portrait?0:(this.camera.aspect>1?-.9:0),portrait?2.6:2.35,0);}else{this.camera.fov=this.camera.aspect<.8?70:60;point(D,this.theta,this.hero.root.position);this.hero.root.position.y+=r.jump;this.hero.root.rotation.set(0,Math.PI-Math.atan(slope(D)),-this.theta,'YXZ');this.camera.position.set(courseX(D-11.5),courseY(D)+7.1,-D+11.5);this.camera.lookAt(courseX(D+18),courseY(D+18)+2.0,-D-18);}
  this.camera.updateProjectionMatrix();this.sky.position.copy(this.camera.position);this.floor.position.z=-D-140;this.sun.position.set(courseX(D)-12,courseY(D)+28,-D+18);this.sun.target.position.set(courseX(D),courseY(D),-D);this.hero.tick(this.elapsed,{...r,moving:!menu&&['running','capture'].includes(this.state)},this.settings);this.hero.root.visible=true;this.shadow.position.copy(this.hero.root.position);this.shadow.position.y-=r.jump;this.shadow.position.y+=.035;this.shadow.material.opacity=.30*(1-r.jump*.14);this.shadow.rotation.z=this.theta;this.shadow.scale.setScalar(1-r.jump*.06);const viewD=menu?0:D;
  for(const batch of this.scenery){let n=0;for(const prop of batch.data){if(prop.s<viewD-26||prop.s>viewD+230)continue;this.dummy.position.set(courseX(prop.s)+prop.side,courseY(prop.s)-.5,-prop.s);this.dummy.rotation.set(0,prop.rot-Math.atan(slope(prop.s)),0);this.dummy.scale.setScalar(prop.scale);this.dummy.updateMatrix();batch.mesh.setMatrixAt(n++,this.dummy.matrix);}batch.mesh.count=n;batch.mesh.instanceMatrix.needsUpdate=true;}
  const counts={gem:0,special:0,rock:0,orb:0,goo:0};let glows=0;for(const it of this.course){if(it.done||it.s<viewD-9)continue;if(it.s>viewD+160)break;const pickup=['gem','special'].includes(it.kind);point(it.s,it.theta,this.dummy.position);if(pickup)this.dummy.position.y+=1.12+Math.sin(this.elapsed*3+it.id)*.16;this.dummy.rotation.set(0,pickup?this.elapsed*(it.kind==='special'?1.0:1.6)+it.id:-Math.atan(slope(it.s)),0);this.dummy.scale.setScalar(1);this.dummy.updateMatrix();this.itemMeshes[it.kind].setMatrixAt(counts[it.kind]++,this.dummy.matrix);if(pickup&&!this.settings.reduced){this.dummy.quaternion.copy(this.camera.quaternion);this.dummy.updateMatrix();this.pickupGlows.setMatrixAt(glows++,this.dummy.matrix);}}
  for(const[kind,m]of Object.entries(this.itemMeshes)){m.count=counts[kind];m.instanceMatrix.needsUpdate=true;}this.pickupGlows.count=glows;this.pickupGlows.instanceMatrix.needsUpdate=true;if(this.state==='running'&&r.power>=25&&!this.settings.reduced){this.trailTimer+=dt;if(this.trailTimer>.09){this.trailTimer=0;this.emit(this.hero.root.position,this.level.accent,r.burst?3:1);}}
  let pn=0;for(const p of this.particles){p.life-=dt;if(p.life<=0)continue;p.pos.addScaledVector(p.vel,dt);p.vel.y-=dt*7;this.dummy.position.copy(p.pos);this.dummy.rotation.set(p.life,p.life*2,p.life);this.dummy.scale.setScalar(p.life/p.max*1.6);this.dummy.updateMatrix();this.particleMesh.setMatrixAt(pn,this.dummy.matrix);this.particleMesh.setColorAt(pn++,new T.Color(p.color));}this.particles=this.particles.filter(p=>p.life>0);this.particleMesh.count=pn;this.particleMesh.instanceMatrix.needsUpdate=true;if(this.particleMesh.instanceColor)this.particleMesh.instanceColor.needsUpdate=true;this.fx=this.fx.filter(f=>{f.age+=dt;if(f.age>=.7){this.scene.remove(f.mesh);f.mesh.geometry.dispose();f.mesh.material.dispose();return false;}f.mesh.scale.setScalar(1+f.age*f.size*2);f.mesh.material.opacity=.7*(1-f.age/.7);return true;});
 }
 clearFX(){for(const f of this.fx){this.scene.remove(f.mesh);f.mesh.geometry.dispose();f.mesh.material.dispose();}this.fx=[];}
 frame(now){const dt=this.last?Math.min((now-this.last)/1000,.05):.016;this.last=now;const frozen=['paused','finished'].includes(this.state);if(!frozen)this.elapsed+=dt;this.tick(dt);this.drawWorld(frozen?0:dt);this.renderer.render(this.scene,this.camera);this.uiTimer+=dt;if(this.uiTimer>.10){this.uiTimer=0;this.events.hud?.(this.run,this.level);}this.raf=requestAnimationFrame(this.frame);}
 dispose(){cancelAnimationFrame(this.raf);window.removeEventListener('resize',this.boundResize);this.audio.stop();this.renderer.dispose();}
}
