import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyStats,stats,normalizeRun,addRun,addToRecord,rankings,medals,progressFromRecords,CATEGORIES} from '../src/shared/center-model.js';
import {RunQueue} from '../src/shared/center-queue.js';
const run=(changes={})=>normalizeRun({mode:'cozy',score:200,complete:true,hits:0,collected:60,total:100,smashes:3,bursts:1,...changes},0,1000);
const player=(uid,points,other={})=>({uid,nickname:uid,active:true,records:{cozy:{...emptyStats(),points,attempts:4},hero:emptyStats()},...other});
test('Six categories with no fabricated champion for a new master',()=>{assert.equal(CATEGORIES.length,6);const master=player('Sean',0,{role:'master',records:{cozy:emptyStats(),hero:emptyStats()}});for(const c of CATEGORIES)assert.deepEqual(rankings([master],'cozy',c.id),[]);});
test('Equal records share competition ranks; hidden and unavailable players excluded',()=>{const rows=rankings([player('Z',100),player('A',100),player('B',50),player('hidden',900,{active:false}),player('missing',800,{unavailable:true})],'cozy');assert.deepEqual(rows.map(r=>[r.uid,r.rank]),[['A',1],['Z',1],['B',3]]);});
test('Difficulty separation and three-attempt minimum average',()=>{const p=player('Sean',200);p.records.cozy.attempts=2;assert.equal(rankings([p],'cozy','average').length,0);p.records.cozy.attempts=3;assert.equal(rankings([p],'cozy','average')[0].value,66.67);assert.equal(rankings([p],'hero').length,0);assert.equal(rankings([p],'unknown').length,0);});
test('Complete, bumped and failed results update medals and clean streak accurately',()=>{let s=addRun(emptyStats(),run());s=addRun(s,run());assert.equal(s.currentStreak,2);assert.equal(s.bestStreak,2);assert.equal(s.points,400);assert.equal(s.completions,2);assert.equal(medals(s),3);s=addRun(s,run({hits:1}));assert.equal(s.currentStreak,0);assert.equal(s.bestStreak,2);const failed=run({complete:false,score:50});assert.equal(failed.medals,0);assert.equal(failed.clean,false);s=addRun(s,failed);assert.equal(s.attempts,4);assert.equal(s.completions,3);assert.equal(s.points,650);assert.equal(s.cleanRuns,2);});
test('A mode update never copies points to the other difficulty',()=>{const record=addToRecord({},run({mode:'hero'}));assert.equal(record.hero.points,200);assert.equal(record.cozy.points,0);assert.equal(progressFromRecords(record,'Sean').name,'Sean');assert.deepEqual(progressFromRecords(record,'Sean').bestHero,[200,0,0]);});
test('Malformed values are sanitized or rejected before queuing',()=>{assert.equal(stats({points:Infinity}).points,0);assert.deepEqual(stats({medals:[8,-2,NaN]}).medals,[7,0,0]);assert.throws(()=>normalizeRun({mode:'unknown',score:100,complete:true},0));assert.throws(()=>normalizeRun({mode:'cozy',score:100,complete:true},4));assert.equal(run({score:900000}).score,500000);});
function storage(){const map=new Map();return {get length(){return map.size;},key:i=>[...map.keys()][i],getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};}
test('Persistent queue uses unique keys across tabs and isolates account owners',()=>{const store=storage(),a=new RunQueue(store),b=new RunQueue(store);a.put('one','a',run());b.put('one','b',run());a.put('two','c',run());assert.equal(new RunQueue(store).entries('one').length,2);assert.equal(new RunQueue(store).entries('two').length,1);a.put('one','a',run());assert.equal(new RunQueue(store).entries('one').length,2);a.remove('one','a');assert.deepEqual(new RunQueue(store).entries('one').map(e=>e.id),['b']);});
test('Unavailable storage retains an in-memory result and reports non-durability',()=>{const q=new RunQueue(null);assert.equal(q.put('owner','id',run()),false);assert.equal(q.entries('owner').length,1);q.remove('owner','id');assert.equal(q.entries('owner').length,0);});
