import {before,after,beforeEach,test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {initializeTestEnvironment,assertSucceeds,assertFails} from '@firebase/rules-unit-testing';
import {doc,setDoc,updateDoc,getDoc,getDocs,collection,query,where,deleteDoc,writeBatch,runTransaction,serverTimestamp,Timestamp} from 'firebase/firestore';
import {addToRecord,emptyStats,normalizeRun} from '../src/shared/center-model.js';
let env;const google=uid=>env.authenticatedContext(uid,{email:uid+'@example.invalid',email_verified:true,firebase:{sign_in_provider:'google.com'}}).firestore();
const member=(nickname='Sean',role='master')=>({nickname,role,active:true,joinedAt:serverTimestamp()});
const run=(changes={})=>normalizeRun({mode:'cozy',score:250,complete:true,hits:0,collected:60,total:100,smashes:3,bursts:1,...changes},0);
async function seed(path,data){await env.withSecurityRulesDisabled(c=>setDoc(doc(c.firestore(),...path.split('/')),data));}
async function register(){const db=google('master');await setDoc(doc(db,'members','master'),member());return db;}
async function submit(db,uid,id,r){return runTransaction(db,async tx=>{const receipt=doc(db,'members',uid,'runs',id),ref=doc(db,'racerRecords',uid);const exists=await tx.get(receipt);if(exists.exists())return;const before=await tx.get(ref);tx.set(receipt,{...r,createdAt:serverTimestamp()});tx.set(ref,{...addToRecord(before.data(),r),lastRunId:id,updatedAt:serverTimestamp()});});}
before(async()=>{if(!process.env.FIRESTORE_EMULATOR_HOST)throw Error('Tests require the local demo emulator, never production.');env=await initializeTestEnvironment({projectId:'demo-james-game-center',firestore:{rules:readFileSync('firestore.rules','utf8')}});});
beforeEach(async()=>{await env.clearFirestore();await seed('_admin/launch',{masterUid:'master'});});after(async()=>env?.cleanup());
test('Only the privately configured master can create the first player; no browser can change bootstrap',async()=>{const db=google('master');await assertSucceeds(setDoc(doc(db,'members','master'),member()));const all=await getDocs(collection(db,'members'));assert.equal(all.size,1);assert.equal(all.docs[0].data().nickname,'Sean');await assertFails(setDoc(doc(google('visitor'),'members','visitor'),member('Visitor','master')));await assertFails(setDoc(doc(google('visitor'),'members','visitor'),member('Visitor','player')));await assertFails(setDoc(doc(db,'_admin','launch'),{masterUid:'visitor'}));await assertFails(deleteDoc(doc(db,'_admin','launch')));});
test('Missing launch config never grants first-visitor master status',async()=>{await env.withSecurityRulesDisabled(c=>deleteDoc(doc(c.firestore(),'_admin','launch')));await assertFails(setDoc(doc(google('visitor'),'members','visitor'),member()));});
test('The sole master cannot be demoted, paused, deleted, or duplicated by browser writes',async()=>{const db=await register();await assertFails(updateDoc(doc(db,'members','master'),{active:false}));await assertFails(updateDoc(doc(db,'members','master'),{role:'player'}));await assertFails(deleteDoc(doc(db,'members','master')));await assertFails(setDoc(doc(db,'members','another-master'),member('Other','master')));});
test('Master can explicitly approve and pause a player; player can only change own nickname',async()=>{const db=await register();await assertSucceeds(setDoc(doc(db,'members','player'),member('Hero','player')));const p=google('player');await assertSucceeds(updateDoc(doc(p,'members','player'),{nickname:'New Hero'}));await assertFails(updateDoc(doc(p,'members','player'),{role:'master'}));await assertFails(updateDoc(doc(p,'members','player'),{active:false}));await assertFails(setDoc(doc(p,'members','friend'),member('Friend','player')));await assertSucceeds(updateDoc(doc(db,'members','player'),{active:false}));await assertFails(getDocs(query(collection(p,'members'),where('active','==',true))));});
test('Visitors, anonymous accounts and unverified identities cannot list cards or read records',async()=>{const master=await register();await submit(master,'master','first',run());const clients=[env.unauthenticatedContext().firestore(),env.authenticatedContext('anon',{firebase:{sign_in_provider:'anonymous'}}).firestore(),google('visitor'),env.authenticatedContext('master',{email_verified:false,firebase:{sign_in_provider:'google.com'}}).firestore()];for(const db of clients){await assertFails(getDocs(collection(db,'members')));await assertFails(getDoc(doc(db,'racerRecords','master')));}await assertFails(getDoc(doc(env.unauthenticatedContext().firestore(),'_admin','launch')));});
test('Approved roster queries expose only active cards and never private run receipts or emails',async()=>{const db=await register();await setDoc(doc(db,'members','player'),member('Hero','player'));await setDoc(doc(db,'members','paused'),member('Paused','player'));await updateDoc(doc(db,'members','paused'),{active:false});await submit(db,'master','first',run());const p=google('player');const list=await assertSucceeds(getDocs(query(collection(p,'members'),where('active','==',true))));assert.equal(list.size,2);assert.ok(list.docs.every(d=>!Object.hasOwn(d.data(),'email')));await assertFails(getDocs(collection(p,'members')));await assertSucceeds(getDoc(doc(p,'racerRecords','master')));await assertFails(getDoc(doc(p,'members','master','runs','first')));await assertFails(getDocs(collection(p,'players')));await assertFails(updateDoc(doc(db,'members','master'),{email:'test@example.invalid'}));});
test('Atomic receipts update records once; retries do not count the same run twice',async()=>{const db=await register(),r=run();await assertSucceeds(submit(db,'master','unique-id',r));await assertSucceeds(submit(db,'master','unique-id',r));const result=(await getDoc(doc(db,'racerRecords','master'))).data();assert.equal(result.cozy.points,250);assert.equal(result.cozy.attempts,1);assert.equal(result.hero.points,0);await assertSucceeds(submit(db,'master','second',run({mode:'hero',score:500})));assert.equal((await getDoc(doc(db,'racerRecords','master'))).data().hero.points,500);});
test('Aggregate edits, receipt-only writes, old receipt reuse and foreign-account writes are denied',async()=>{const db=await register(),r=run();await assertFails(setDoc(doc(db,'members','master','runs','alone'),{...r,createdAt:serverTimestamp()}));await assertFails(setDoc(doc(db,'racerRecords','master'),{cozy:emptyStats(),hero:emptyStats(),lastRunId:'missing',updatedAt:serverTimestamp()}));await submit(db,'master','first',r);await assertFails(updateDoc(doc(db,'racerRecords','master'),{'cozy.points':999999,updatedAt:serverTimestamp()}));await assertFails(updateDoc(doc(db,'members','master','runs','first'),{score:900}));await assertFails(deleteDoc(doc(db,'members','master','runs','first')));await setDoc(doc(db,'members','player'),member('Hero','player'));await assertFails(submit(google('player'),'master','foreign',r));const batch=writeBatch(db),next=addToRecord((await getDoc(doc(db,'racerRecords','master'))).data(),r);next.cozy.points+=1;batch.set(doc(db,'members','master','runs','wrong'),{...r,createdAt:serverTimestamp()});batch.set(doc(db,'racerRecords','master'),{...next,lastRunId:'wrong',updatedAt:serverTimestamp()});await assertFails(batch.commit());});
test('Clean streaks and medal masks match the shared model across modes and failed attempts',async()=>{const db=await register();for(const [id,r] of [['a',run()],['b',run()],['c',run({hits:1,collected:20})],['d',run({complete:false,score:50})]])await assertSucceeds(submit(db,'master',id,r));const data=(await getDoc(doc(db,'racerRecords','master'))).data();assert.equal(data.cozy.attempts,4);assert.equal(data.cozy.completions,3);assert.equal(data.cozy.bestStreak,2);assert.equal(data.cozy.currentStreak,0);assert.deepEqual(data.cozy.medals,[7,0,0]);});
test('Bounded run validation rejects extra fields and invalid scores even with matching summaries',async()=>{const db=await register();for(const [i,changes] of [{score:500001},{score:-1},{clean:true,complete:false},{mode:'invalid'},{email:'leak@example.invalid'},{createdAt:Timestamp.fromMillis(1)}].entries()){const r={...run(),...changes},b=writeBatch(db);b.set(doc(db,'members','master','runs','invalid-'+i),{...r,createdAt:changes.createdAt||serverTimestamp()});b.set(doc(db,'racerRecords','master'),{...addToRecord({},r),lastRunId:'invalid-'+i,updatedAt:serverTimestamp()});await assertFails(b.commit());}});
