import './community.css';
import {icon,esc,toast,RACER} from './ui.js';
import {settings,usePlayerProfile} from './profile.js';
import {MODES,WORLDS,CATEGORIES,stats,medals,rankings,normalizeRun,progressFromRecords} from './center-model.js';
import {RunQueue} from './center-queue.js';
settings.cloud=false; // Ranked accounts replace automatic anonymous backup, not saved practice.
const number=n=>new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(n||0);
const initials=n=>Array.from(n||'H').slice(0,2).join('').toUpperCase();
const role=p=>p.role==='master'?'Master':'Player';
const avatar=p=>`<span class="jc-avatar ${p.role==='master'?'master':''}">${esc(initials(p.nickname))}</span>`;
const badge=p=>`<span class="jc-badge ${p.role==='master'?'master':''}">${icon(p.role==='master'?'shield':'user')}${role(p)}</span>`;
const stored=key=>{try{return localStorage.getItem(key);}catch{return null;}};
export function installCommunity({beforeOpen=()=>{}}={}){const c=new Community(beforeOpen);if(['localhost','127.0.0.1'].includes(location.hostname))window.__jamesCommunity=c;return c;}
class Community{
 constructor(beforeOpen){
  this.beforeOpen=beforeOpen;this.mode='cozy';this.category='points';this.view='hall';this.rows=[];this.generation=0;this.owner=null;this.syncText='Practice stays on this device. Sign in for player records.';this.search='';this.page=0;
  let storage;try{storage=localStorage;}catch{storage=null;}this.queue=new RunQueue(storage);
  const launcher=document.createElement('section');launcher.className='jc-launcher';launcher.setAttribute('aria-label','James player headquarters');launcher.innerHTML=`<div><span class="eyebrow">YOUR HERO HEADQUARTERS</span><strong>Big wins. Lasting memories.</strong></div><nav><button class="btn secondary" data-community="hall">${icon('trophy')} Hall of Fame</button><button class="btn secondary" data-community="players">${icon('user')} Player Cards</button><button class="text-btn" data-community="mine">My Player Card ${icon('right')}</button><button class="text-btn" data-community="master" data-jc-master hidden>${icon('shield')} Master Controls</button></nav>`;
  const welcome=document.querySelector('.welcome-bar');if(welcome)welcome.after(launcher);else document.querySelector('.intro-links')?.after(launcher);
  const wrap=document.createElement('div');wrap.innerHTML=`<dialog class="jc-dialog" id="jc-center" aria-labelledby="jc-title"><header class="jc-dialog-head"><div><span class="eyebrow">JAMES GAME CENTER</span><h2 id="jc-title">Hall of Fame</h2></div><button class="icon-btn" data-action="close-center" aria-label="Close player headquarters">${icon('close')}</button></header><nav class="jc-tabs" aria-label="Player headquarters"><button data-community="hall">${icon('trophy')} Hall of Fame</button><button data-community="players">${icon('user')} Player Cards</button><button data-community="master" data-jc-master hidden>${icon('shield')} Master Controls</button></nav><div class="jc-dialog-body"><div class="jc-toolbar"><div class="jc-modes" aria-label="Score difficulty"><button data-action="mode" data-score-mode="cozy">Little Hero</button><button data-action="mode" data-score-mode="hero">Superhero</button></div><button class="text-btn" data-action="refresh">Refresh</button></div><p class="jc-sync" role="status"></p><div id="jc-content"></div></div></dialog><dialog class="jc-dialog jc-player-dialog" id="jc-player" aria-labelledby="jc-player-title"><header class="jc-dialog-head"><div><span class="eyebrow">LIFETIME PLAYER CARD</span><h2 id="jc-player-title">Player</h2></div><button class="icon-btn" data-action="close-player" aria-label="Close player card">${icon('close')}</button></header><div id="jc-player-content" class="jc-dialog-body"></div></dialog>`;
  document.body.append(wrap);this.dialog=document.getElementById('jc-center');this.card=document.getElementById('jc-player');this.body=document.getElementById('jc-content');
  const panel=document.querySelector('#profile-dialog .cloud-panel');if(panel){panel.id='jc-account-panel';panel.innerHTML='';}
  document.addEventListener('click',e=>{if(e.target.closest('[data-dialog="profile"]'))this.ensure();const b=e.target.closest('[data-community],[data-action]');if(!b||b.disabled)return;if(b.dataset.community){this.open(b.dataset.community);return;}this.action(b).catch(error=>{this.syncText=error.message||'Please try again.';this.updateStatus();toast(this.syncText);});});
  document.getElementById('nickname-form')?.addEventListener('submit',e=>{if(!this.service?.member)return;e.preventDefault();e.stopImmediatePropagation();this.service.rename(document.getElementById('nickname').value).then(()=>toast('Player nickname saved.')).catch(error=>toast(error.message));},true);
  this.dialog.addEventListener('close',()=>{++this.generation;});for(const d of[this.dialog,this.card])d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();});
  window.addEventListener('online',()=>this.flush());window.addEventListener('storage',e=>{if(e.key==='james-center:accounts:enabled'&&!this.service)this.ensure();if(e.key?.startsWith('james-center:run:v1:'))this.flush();});
  this.renderAccount();this.updateStatus();if(stored('james-center:accounts:enabled'))this.ensure();
 }
 async ensure(){if(this.connecting)return this.connecting;if(this.service?.ready)return this.service;this.connecting=(async()=>{try{this.connectionError='';const {CenterService}=await import('./center-service.js');const service=new CenterService();this.useService(service);await service.init();return service;}catch(e){this.unsubscribe?.();this.service=null;this.connectionError='Account connection is unavailable. Try again online.';this.renderAccount();if(this.dialog.open)this.renderLocked();return null;}finally{this.connecting=null;}})();return this.connecting;}
 // Injected adapters are used only by local tests. Database permissions are always server enforced.
 useService(service){this.unsubscribe?.();this.service=service;this.unsubscribe=service.subscribe(()=>this.sessionChanged());this.sessionChanged();}
 sessionChanged(){const s=this.service;if(!s)return;if(s.loading){this.renderAccount();return;}const uid=s.member?.uid||null,changed=uid!==this.owner;
  if(changed){this.owner=uid;this.rows=[];this.card.close();++this.generation;usePlayerProfile(uid,s.member?.nickname);}else if(s.member)usePlayerProfile(uid,s.member.nickname);
  this.renderAccount();document.querySelectorAll('[data-jc-master]').forEach(e=>e.hidden=s.member?.role!=='master');if(uid)this.flush();else this.syncText=s.problem||'Practice stays on this device. Sign in for player records.';
  this.updateStatus();if(this.dialog.open){if(uid)this.load();else this.renderLocked();}
 }
 beginRun(){if(!this.service?.member||this.service.loading)return null;return{uid:this.service.member.uid,id:crypto.randomUUID()};}
 finishRun(token,result,index){if(!token)return;try{const run=normalizeRun(result,index),durable=this.queue.put(token.uid,token.id,run);this.syncText=durable?'Run saved on this device. Uploading player records…':'Browser storage is unavailable. Keep this page open until the run uploads.';this.updateStatus();this.flush();}catch(e){this.syncText=e.message;this.updateStatus();}}
 async flush(){if(this.flushing||!this.service?.member)return;this.flushing=true;const s=this.service,uid=s.member.uid;try{
  let pending=this.queue.entries(uid);while(pending.length&&this.service===s&&s.member?.uid===uid){const entry=pending[0];await s.submit(uid,entry.id,entry.run);this.queue.remove(uid,entry.id);pending=this.queue.entries(uid);}
  if(s.member?.uid===uid){this.syncText='Player records are up to date.';await this.refreshOwn();}
 }catch{this.syncText='Records could not sync. Pending runs stay on this device; reconnect or press Refresh.';}finally{this.flushing=false;this.updateStatus();}}
 async refreshOwn(){const s=this.service,uid=s?.member?.uid;if(!uid)return;try{const record=await s.ownRecord();if(this.service===s&&s.member?.uid===uid&&!this.queue.entries(uid).length)usePlayerProfile(uid,s.member.nickname,progressFromRecords(record,s.member.nickname));}catch{this.syncText='Saved player records could not load. Your cached progress has not been replaced.';this.updateStatus();}}
 updateStatus(){const pending=this.owner?this.queue.entries(this.owner).length:0;for(const el of document.querySelectorAll('.jc-sync'))el.textContent=this.syncText+(pending?` ${pending} pending run${pending===1?'':'s'}.`:'');}
 accountMarkup(){const s=this.service,member=s?.member,user=s?.user,signed=Boolean(user&&!user.isAnonymous),ready=Boolean(s?.ready&&!s.loading);
  return `<div class="jc-account"><span class="eyebrow">${member?'YOUR JAMES ACCOUNT':'MASTER-ONLY LAUNCH'}</span><h3>${member?`${icon('shield')} ${esc(member.nickname)}`:'One account. All your James adventures.'}</h3><p>${member?`${role(member)} access · Signed-in results appear on your player card and the Hall of Fame.`:'Sign in to your approved James account. Visitors can practice without creating a player card.'}</p>${s?.problem?`<p class="jc-warning" role="status">${esc(s.problem)}</p>`:''}${this.connectionError?`<p class="jc-warning">${esc(this.connectionError)}</p><button class="btn secondary" data-action="connect">Retry account connection</button>`:''}<div class="jc-account-actions">${!signed?`<button class="btn" data-action="login" ${ready?'':'disabled'}>${icon('user')} ${ready?'Sign in with Google':'Preparing sign-in…'}</button>`:`${member?`<button class="btn" data-community="mine">${icon('user')} My Player Card</button>`:''}<button class="btn secondary" data-action="account-refresh">Check access</button><button class="text-btn" data-action="logout">Sign out</button>`}</div>${signed?`<details class="jc-uid"><summary>Account setup · Your User ID</summary><p>This identifies your James Firebase account. It is not a password. Only the privately configured master can activate the first player card.</p><code>${esc(user.uid)}</code><button class="text-btn" data-action="copy-uid">Copy User ID</button></details>`:''}<p class="small-note">No imported accounts, sample players, or automatic player signup. Google sign-in verifies your identity; the approval list controls access.</p><p class="jc-sync" role="status"></p></div>`;
 }
 renderAccount(){const panel=document.getElementById('jc-account-panel');if(panel){panel.innerHTML=this.accountMarkup();panel.querySelector('.jc-sync').id='cloud-status';}const note=document.getElementById('nickname-note');if(note)note.textContent=this.service?.member?'Only your nickname appears on player cards. Your email is never listed.':'Practice nickname only. Sign in below for your approved player account.';this.updateStatus();}
 open(view='hall'){this.beforeOpen();document.getElementById('profile-dialog')?.close();this.view=view==='mine'?'players':view;this.openMine=view==='mine';this.page=0;this.search='';if(!this.dialog.open)this.dialog.showModal();this.configureTabs();if(!this.service?.member){this.renderLocked();this.ensure();}else this.load();}
 configureTabs(){document.getElementById('jc-title').textContent=this.view==='master'?'Master Controls':this.view==='players'?'Player Cards':'Hall of Fame';this.dialog.querySelectorAll('[data-community]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.community===this.view)));this.dialog.querySelector('.jc-toolbar').hidden=!this.service?.member;this.dialog.querySelector('.jc-modes').hidden=this.view==='master';this.dialog.querySelectorAll('[data-action="mode"]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scoreMode===this.mode)));}
 renderLocked(){this.configureTabs();this.body.innerHTML=this.accountMarkup();this.updateStatus();}
 async load(){if(!this.service?.member){this.renderLocked();return;}this.configureTabs();const ticket=++this.generation,s=this.service,uid=s.member.uid;this.body.innerHTML='<p class="jc-empty" role="status">Loading player records…</p>';try{const rows=await s.roster(this.view==='master');if(ticket!==this.generation||!this.dialog.open||s.member?.uid!==uid)return;this.rows=rows;this.draw();if(this.openMine){this.openMine=false;const mine=rows.find(p=>p.uid===uid);if(mine)this.showCard(mine);}}catch{if(ticket===this.generation){this.rows=[];this.body.innerHTML='<div class="jc-empty"><h3>Records unavailable</h3><p>Nothing has been replaced with zeroes. Check your connection and use Refresh.</p></div>';}}}
 draw(){if(this.view==='players')this.drawPlayers();else if(this.view==='master')this.drawMaster();else this.drawHall();}
 drawHall(){if(this.rows.some(p=>p.unavailable)){this.body.innerHTML='<div class="jc-empty"><h3>Some records could not load</h3><p>Rankings are paused rather than naming an incorrect champion. Use Refresh to try again.</p></div>';return;}
  const category=CATEGORIES.find(c=>c.id===this.category)||CATEGORIES[0],ranked=rankings(this.rows,this.mode,this.category),winners=ranked.filter(p=>p.rank===1);
  this.body.innerHTML=`<div class="jc-hall-intro"><span class="jc-cup">${icon('trophy')}</span><div><span class="eyebrow">LITTLE HEROES. LEGENDARY MOMENTS.</span><h3>A place in the Hall.</h3><p>${MODES[this.mode]} records · Jamesy The Hulk Racer</p></div></div><div class="jc-award-grid">${CATEGORIES.map(c=>{const leaders=rankings(this.rows,this.mode,c.id).filter(p=>p.rank===1);return `<button class="jc-award ${this.category===c.id?'selected':''}" data-action="category" data-category="${c.id}" aria-pressed="${this.category===c.id}"><span class="jc-award-icon">${icon(c.icon)}</span><strong>${c.title}</strong><b>${leaders.length?number(leaders[0].value):'—'}</b><span>${leaders.length?leaders.slice(0,3).map(p=>esc(p.nickname)).join(' · ')+(leaders.length>3?` +${leaders.length-3}`:''):'First record awaits'}</span><small>${c.label}</small></button>`;}).join('')}</div><section class="jc-leaderboard"><div class="jc-table-heading"><div><span class="eyebrow">${winners.length>1?'CO-CHAMPIONS WELCOME':'THE ALL-TIME RECORD BOOK'}</span><h3>${category.title}</h3></div><span>${ranked.length} ranked ${ranked.length===1?'player':'players'}</span></div>${ranked.length?`<div class="jc-table-scroll"><table><thead><tr><th scope="col">Rank</th><th scope="col">Player</th><th scope="col">${category.id==='average'?'Avg. points':category.title.replace('Most ','').replace('Highest ','')}</th></tr></thead><tbody>${ranked.slice(this.page*12,(this.page+1)*12).map(p=>`<tr class="${p.rank===1?'champion':''}"><td><span class="jc-rank">${p.rank===1?icon('trophy'):''}#${p.rank}</span></td><td><button class="jc-player-link" data-action="player" data-uid="${esc(p.uid)}">${avatar(p)}<span><strong>${esc(p.nickname)}</strong><small>${role(p)}${p.uid===this.owner?' · You':''}</small></span></button></td><td><strong>${number(p.value)}</strong></td></tr>`).join('')}</tbody></table></div>${this.pager(ranked.length)}`:`<div class="jc-empty"><h4>${category.id==='average'?'Three adventures unlock this record.':'Your first record is waiting.'}</h4><p>${category.id==='average'?'Finish three attempts in this difficulty to join the average-points category.':'Finish an adventure while signed in. There are no sample scores or automatic first-place awards.'}</p></div>`}</section><p class="small-note">Equal values share the same rank. Difficulty records stay separate. Failed Superhero attempts count as adventures; leaving mid-run does not. Scores are for friendly family play, not cheat-proof competition.</p>`;
 }
 pager(total){return total>12?`<div class="jc-paging"><button class="text-btn" data-action="page" data-step="-1" ${this.page===0?'disabled':''}>Previous</button><span>${this.page+1} / ${Math.ceil(total/12)}</span><button class="text-btn" data-action="page" data-step="1" ${(this.page+1)*12>=total?'disabled':''}>Next</button></div>`:'';}
 drawPlayers(){const matches=this.rows.filter(p=>p.active!==false&&p.nickname.toLocaleLowerCase().includes(this.search.toLocaleLowerCase()));this.body.innerHTML=`<div class="jc-cards-intro"><h3>Your people. Their hero stories.</h3><p>${this.rows.filter(p=>p.active!==false).length} approved ${this.rows.length===1?'player':'players'} · Only explicitly approved accounts appear here.</p><label for="jc-search">Find a player by nickname</label><input type="search" id="jc-search" maxlength="40" placeholder="Find a hero…" value="${esc(this.search)}"></div><div class="jc-card-grid" id="jc-card-grid">${this.playerTiles(matches)}</div>${this.pager(matches.length)}`;document.getElementById('jc-search').addEventListener('input',e=>{this.search=e.target.value;this.page=0;const all=this.rows.filter(p=>p.active!==false&&p.nickname.toLocaleLowerCase().includes(this.search.toLocaleLowerCase()));document.getElementById('jc-card-grid').innerHTML=this.playerTiles(all);this.body.querySelector('.jc-paging')?.remove();document.getElementById('jc-card-grid').insertAdjacentHTML('afterend',this.pager(all.length));});}
 playerTiles(rows){return rows.slice(this.page*12,(this.page+1)*12).map(p=>{const s=stats(p.records?.[this.mode]),rank=rankings(this.rows,this.mode).find(r=>r.uid===p.uid)?.rank;return `<button class="jc-player-tile" data-action="player" data-uid="${esc(p.uid)}"><div class="jc-card-top">${avatar(p)}${badge(p)}</div><strong class="jc-card-name">${esc(p.nickname)}${p.uid===this.owner?'<small>You</small>':''}</strong><span class="jc-card-rank">${p.unavailable?'Records unavailable':this.rows.some(p=>p.unavailable)?'Ranking unavailable':rank?`#${rank} · All-time points`:'Unranked · First adventure awaits'}</span><div class="jc-tile-stats"><span><b>${p.unavailable?'—':number(s.points)}</b>Points</span><span><b>${p.unavailable?'—':number(s.attempts)}</b>Adventures</span><span><b>${p.unavailable?'—':medals(s)+'/9'}</b>Medals</span></div><span class="jc-card-open">Open player card ${icon('right')}</span></button>`;}).join('')||'<p class="jc-empty">No player matches that nickname.</p>';}
 showCard(p){this.selectedPlayer=p;document.getElementById('jc-player-title').textContent=p.nickname;const s=stats(p.records?.[this.mode]),rank=this.rows.some(p=>p.unavailable)?null:rankings(this.rows,this.mode).find(r=>r.uid===p.uid)?.rank;
  const values=[['Total points',number(s.points)],['Adventures played',number(s.attempts)],['Worlds completed',number(s.completions)],['Average / adventure',s.attempts?(s.points/s.attempts).toFixed(2):'—'],['Best run',number(s.best)],['Best clean streak',number(s.bestStreak)],['Treasures collected',number(s.treasures)],['Obstacles smashed',number(s.smashes)],['Super-power bursts',number(s.bursts)],['No-bump finishes',number(s.cleanRuns)],['Completion rate',s.attempts?Math.round(s.completions/s.attempts*100)+'%':'—'],['World medals',medals(s)+' / 9']];
  document.getElementById('jc-player-content').innerHTML=`<div class="jc-player-banner">${avatar(p)}<div>${badge(p)}<h3>${esc(p.nickname)}</h3><p>${p.uid===this.owner?'Your lifetime player card':'Lifetime player card'}</p></div></div><div class="jc-game-line"><img src="${RACER}assets/icon-192.png" alt=""><div><strong>Jamesy The Hulk Racer</strong><small>${MODES[this.mode]} · ${p.unavailable?'Unavailable':rank?'#'+rank+' all-time points':'Unranked'}</small></div></div><div class="jc-modes"><button data-action="card-mode" data-score-mode="cozy" aria-pressed="${this.mode==='cozy'}">Little Hero</button><button data-action="card-mode" data-score-mode="hero" aria-pressed="${this.mode==='hero'}">Superhero</button></div>${p.unavailable?'<p class="jc-warning">These records could not load. Close this card and use Refresh.</p>':`<dl class="jc-stat-grid">${values.map(([label,value])=>`<div><dt>${label}</dt><dd>${value}</dd></div>`).join('')}</dl><section class="jc-world-records"><h4>World records</h4>${WORLDS.map((w,i)=>`<div><strong>${w}</strong><span>${number(s.worldBest[i])} best</span><span class="jc-medals" aria-label="${((s.medals[i]&1)+((s.medals[i]>>1)&1)+((s.medals[i]>>2)&1))} of 3 medals">${[1,2,4].map(b=>icon('star',s.medals[i]&b?'earned':'')).join('')}</span></div>`).join('')}</section><p class="small-note">${s.lastPlayed?'Last played '+new Date(s.lastPlayed).toLocaleDateString():'No signed-in adventures yet. Your player card is ready for the first one.'}</p>`}<button class="btn secondary" data-action="card-hall">${icon('trophy')} View Hall of Fame</button>`;
  if(!this.card.open)this.card.showModal();
 }
 drawMaster(){if(this.service?.member?.role!=='master'){this.body.innerHTML='<p class="jc-empty">Only the master account can open these controls.</p>';return;}this.body.innerHTML=`<div class="jc-master-intro">${icon('shield')}<div><h3>One founding master. You.</h3><p>Your master account cannot be disabled, reassigned, or duplicated here. No other players are added automatically.</p></div></div><div class="jc-admin-list">${this.rows.map(p=>`<article>${avatar(p)}<div><strong>${esc(p.nickname)}</strong><span>${role(p)} · ${p.active?'Active':'Paused'}</span></div>${p.role==='master'?'<span class="jc-badge master">Protected</span>':`<button class="text-btn" data-action="active" data-uid="${esc(p.uid)}" data-active="${!p.active}">${p.active?'Pause access':'Restore access'}</button>`}</article>`).join('')}</div><details class="jc-add-player"><summary>Add a player later</summary><p>Leave this closed to keep the roster master-only. For a future player, have them sign in with Google and share their James User ID. Confirm the ID belongs to the intended person.</p><form id="jc-approve-form"><label for="jc-new-uid">Firebase User ID</label><input id="jc-new-uid" required maxlength="128" autocomplete="off" placeholder="Exact User ID from their James account"><label for="jc-new-name">Player nickname</label><input id="jc-new-name" required maxlength="20" autocomplete="off"><label class="jc-confirm"><input id="jc-approve-confirm" type="checkbox" required> I intend to approve this additional player.</label><button class="btn" type="submit">Approve player</button><p id="jc-admin-status" role="status"></p></form></details><p class="small-note">Pausing access hides a player from the active roster and blocks shared-record access without deleting progress. These controls never modify the other Game Centers.</p>`;
  document.getElementById('jc-approve-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;const status=document.getElementById('jc-admin-status');status.textContent='Approving…';try{await this.service.approve(document.getElementById('jc-new-uid').value.trim(),document.getElementById('jc-new-name').value);await this.load();toast('Player approved.');}catch(error){status.textContent=error.message;button.disabled=false;}};
 }
 async action(b){const a=b.dataset.action;if(a==='close-center')return this.dialog.close();if(a==='close-player')return this.card.close();if(a==='connect'){await this.ensure();return;}if(a==='login'){try{localStorage.setItem('james-center:accounts:enabled','1');}catch{}await this.service?.login();return;}if(a==='logout'){await this.service?.logout();return;}if(a==='account-refresh'){await this.service?.refresh();return;}if(a==='copy-uid'){try{await navigator.clipboard.writeText(this.service.user.uid);toast('James User ID copied.');}catch{toast('Select the User ID above and copy it.');}return;}if(a==='refresh'){await this.service?.refresh();await this.flush();await this.load();return;}if(a==='mode'||a==='card-mode'){if(!Object.hasOwn(MODES,b.dataset.scoreMode))return;this.mode=b.dataset.scoreMode;this.page=0;this.configureTabs();this.draw();if(a==='card-mode')this.showCard(this.selectedPlayer);return;}if(a==='category'){this.category=b.dataset.category;this.page=0;this.drawHall();return;}if(a==='page'){this.page=Math.max(0,this.page+Number(b.dataset.step));this.draw();return;}if(a==='player'){const p=this.rows.find(p=>p.uid===b.dataset.uid);if(p)this.showCard(p);return;}if(a==='card-hall'){this.card.close();this.open('hall');return;}if(a==='active'&&confirm('Change access for this player? Their saved records will not be deleted.')){await this.service.setActive(b.dataset.uid,b.dataset.active==='true');await this.load();}}
}
