import {profile,settings,rename,saveSettings,connectCloud,medalCount,trophies,storageAvailable} from './profile.js';
const paths={home:'M3 11 12 3l9 8M5 10v10h5v-6h4v6h5V10',play:'m8 4 12 8-12 8Z',pause:'M8 5v14M16 5v14',back:'m14 5-7 7 7 7M7 12h14',right:'m9 5 7 7-7 7',left:'m15 5-7 7 7 7',jump:'m6 10 6-6 6 6M12 4v16',bolt:'m14 2-10 12h7l-1 8 10-13h-7Z',star:'m12 2 3 6 7 1-5 5 1 8-6-4-6 4 1-8-5-5 7-1Z',gem:'m12 2 9 7-9 13L3 9ZM3 9h18M12 2 8 9l4 13 4-13Z',shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6Z',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2',user:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM4 21v-3a8 6 0 0 1 16 0v3',help:'M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 4M12 18h.01M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20',close:'m6 6 12 12M6 18 18 6',volume:'m3 9 5 0 5-5v16l-5-5H3ZM17 8q5 4 0 8',expand:'M3 9V3h6M15 3h6v6M21 15v6h-6M9 21H3v-6',flag:'M5 22V3m0 1c5-5 9 5 15 0v11c-6 5-10-5-15 0',sun:'M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10ZM12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2',globe:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20ZM2 12h20M12 2c-6 6-6 14 0 20 6-6 6-14 0-20',cloud:'M6 18a5 5 0 1 1 1-10 6 6 0 0 1 11 1 4 4 0 1 1 0 9Z',check:'m4 12 5 5L20 6',trophy:'M8 3h8v8a4 4 0 0 1-8 0ZM8 5H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4M12 15v6M8 21h8'};
export const icon=(name,cls='')=>`<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.star}"/></svg>`;
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const HUB='/James-Game-Center/',RACER='/James-Hulk-Racer/';
export function brand(sub='Game Center'){return `<a class="brand" href="${HUB}" aria-label="James Game Center"><span class="brand-mark">J<span>4</span></span><span><strong>JAMES</strong><small>${sub}</small></span></a>`;}
export function header(sub='Game Center'){return `<header class="site-header">${brand(sub)}<nav aria-label="Main navigation"><button class="icon-btn" data-dialog="help" aria-label="How to play">${icon('help')}</button><button class="icon-btn" data-dialog="settings" aria-label="Settings">${icon('settings')}</button><button class="profile-btn" data-dialog="profile">${icon('user')}<span data-name></span></button></nav></header>`;}
let toastTimer;
export function toast(text){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.setAttribute('role','status');document.body.append(t);}t.textContent=text;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),4200);}
export function installDialogs(onSettings=()=>{},beforeOpen=()=>{}){
 const wrap=document.createElement('div');wrap.innerHTML=`
 <dialog id="help-dialog" class="panel-dialog"><div class="dialog-title"><span class="eyebrow">HERO TRAINING</span><button class="icon-btn" data-close aria-label="Close">${icon('close')}</button></div><h2>Big powers.<br>Little instructions.</h2><div class="instruction-grid"><div>${icon('gem')}<h3>Collect & glow</h3><p>Follow the treasures. Your power grows with every pickup.</p></div><div>${icon('jump')}<h3>Dodge & jump</h3><p>Move across the half-pipe. Jump over rocks, goo and floating bumpers.</p></div><div>${icon('bolt')}<h3>Jamesy smash!</h3><p>25 power unlocks Smash. At 65, unlock Thunderclap and a gem magnet. Fill the meter for a super-powered rush.</p></div></div><div class="help-keys"><p><strong>Touch:</strong> Hold the left / right arrows, or swipe across the track. Tap Jump, Smash or Clap.</p><p><strong>Keyboard:</strong> ← → or A / D to steer · Space to jump · S to smash · C to clap · Esc to pause.</p></div><p class="small-note">Little Hero has a gentler pace and no game-over. Superhero is faster and gives you three shields. All three worlds are ready to explore.</p><details><summary>Add to your home screen</summary><p>On iPhone or iPad, open in Safari, tap Share, then Add to Home Screen. On Android, use your browser’s Install app or Add to Home screen option. Landscape gives you a wider view.</p></details></dialog>
 <dialog id="settings-dialog" class="panel-dialog"><div class="dialog-title"><span class="eyebrow">MAKE IT YOURS</span><button class="icon-btn" data-close aria-label="Close">${icon('close')}</button></div><h2>Hero settings</h2><label class="range-label">Music <input id="music-setting" type="range" min="0" max="1" step=".05" value="${settings.music}"></label><label class="range-label">Sound effects <input id="sfx-setting" type="range" min="0" max="1" step=".05" value="${settings.sfx}"></label><label class="switch-label"><span>Gentle effects<small>Less glow, no particles or expanding power rings.</small></span><input id="reduced-setting" type="checkbox" ${settings.reduced?'checked':''}></label><label class="select-label">Graphics <select id="quality-setting"><option value="auto">Auto · recommended</option><option value="high">High · dynamic shadows</option><option value="low">Lightweight · save battery</option></select></label><p class="small-note">Sound starts after you press Play. The game pauses when you switch apps.</p><button class="btn secondary" id="fullscreen-btn">${icon('expand')} Full screen</button></dialog>
 <dialog id="profile-dialog" class="panel-dialog"><div class="dialog-title"><span class="eyebrow">YOUR HERO CARD</span><button class="icon-btn" data-close aria-label="Close">${icon('close')}</button></div><div class="profile-heading"><span class="brand-mark large">J<span>4</span></span><div><h2 data-name></h2><p>Every great adventure starts with you.</p></div></div><form id="nickname-form"><label for="nickname">Hero nickname</label><div class="input-row"><input id="nickname" maxlength="20" autocomplete="nickname" required aria-describedby="nickname-note"><button class="btn" type="submit">Save</button></div><small id="nickname-note">Use a nickname, not your full name. No email required.</small></form><div class="stats-grid"><div><strong data-runs></strong><span>Adventures</span></div><div><strong data-gems></strong><span>Treasures</span></div><div><strong data-medals></strong><span>World medals</span></div></div><div class="cloud-panel"><h3>${icon('cloud')} Private backup</h3><p id="cloud-status" role="status">Your progress saves on this device.</p><button class="btn secondary" id="connect-cloud">Connect cloud backup</button><details><summary>For grown-ups</summary><p>Backup uses a private anonymous account in the James Game Center Firebase project. It is shared by the hub and racer in the same browser. It is not a cross-device login: clearing browser data can lose access to an anonymous account. No public profiles, chat, analytics or advertising are included.</p></details></div></dialog>
 <dialog id="trophies-dialog" class="panel-dialog"><div class="dialog-title"><span class="eyebrow">LITTLE WINS, BIG SMILES</span><button class="icon-btn" data-close aria-label="Close">${icon('close')}</button></div><h2>Your trophy room</h2><div id="trophy-grid" class="trophy-grid"></div><p class="small-note">Earn a medal for finishing a world, collecting at least half its treasures, and finishing without a bump. Replay to collect all nine.</p></dialog>`;
 document.body.append(wrap);wrap.querySelector('#quality-setting').value=settings.quality;
 document.querySelectorAll('[data-dialog]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.dialog)));
 wrap.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
 wrap.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
 document.getElementById('nickname-form').addEventListener('submit',e=>{e.preventDefault();rename(document.getElementById('nickname').value);refresh();toast('Hero nickname saved.');});
 for(const key of['music','sfx','reduced','quality'])document.getElementById(`${key}-setting`).addEventListener('input',e=>{settings[key]=key==='reduced'?e.target.checked:key==='quality'?e.target.value:Number(e.target.value);saveSettings();onSettings();});
 document.getElementById('connect-cloud').onclick=async e=>{e.target.disabled=true;await connectCloud();e.target.disabled=false;};
 document.getElementById('fullscreen-btn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('Use Add to Home Screen for the full-screen iPhone experience.');}catch{toast('This browser does not allow full screen here.');}};
 window.addEventListener('james-profile',refresh);window.addEventListener('james-cloud',e=>{document.getElementById('cloud-status').textContent=e.detail;});
 function refresh(){document.querySelectorAll('[data-name]').forEach(n=>n.textContent=profile.name);document.getElementById('nickname').value=profile.name;document.querySelectorAll('[data-runs]').forEach(n=>n.textContent=profile.runs.toLocaleString());document.querySelectorAll('[data-gems]').forEach(n=>n.textContent=profile.gems.toLocaleString());document.querySelectorAll('[data-medals]').forEach(n=>n.textContent=`${medalCount()} / 9`);document.getElementById('trophy-grid').innerHTML=trophies().map(t=>`<article class="trophy ${t.earned?'earned':''}">${icon(t.icon)}<h3>${t.title}</h3><p>${t.description}</p><span>${t.earned?'Earned':'Keep exploring'}</span></article>`).join('');if(!storageAvailable)document.getElementById('cloud-status').textContent='Browser storage is unavailable. Progress lasts only for this visit.';}
 function open(name){beforeOpen();refresh();document.getElementById(`${name}-dialog`)?.showModal();}
 refresh();if(settings.cloud)connectCloud();return{open,refresh};
}
