import './style.css';
import {loadArt,assetURL} from './assets.js';
import {EmeraldPreview} from './engine.js';
import {AudioEngine} from '../game/audio.js';

const app=document.querySelector('#app');
app.innerHTML=`<canvas id="game" aria-label="Jamesy running through a curved Emerald Park half-pipe"></canvas>
<header><div class="brand"><span class="crest">J</span><span>JAMESY<small>EMERALD PARK</small></span></div><div class="header-actions"><button id="library-button">Art & motion</button><button id="sound" aria-pressed="false" aria-label="Enable sound">Sound off</button><button id="pause" hidden>Pause</button></div></header>
<div id="hud" hidden><div class="score-box"><span class="gem-icon">◆</span><strong id="gems">0</strong><span class="star-icon">★</span><strong id="stars">0</strong><small id="score">0 points</small></div><div class="power-box"><div><strong>SUPER POWER</strong><span id="power-label">0%</span></div><div class="power-track"><div id="power-fill"></div></div><div class="distance-track"><div id="distance-fill"></div></div></div></div>
<section id="welcome" class="panel welcome"><span class="eyebrow">JAMESY'S FIRST ADVENTURE</span><h1>A little hero.<br>A big adventure.</h1><p>Race through Emerald Park. Gather power gems, jump over goo, and smash a path through the rocks.</p><button class="primary" id="start" disabled>Preparing the park…</button><p class="keys"><b>← → / A D</b> Steer up the walls<br><b>Space</b> Jump &nbsp; <b>X</b> Smash &nbsp; <b>C</b> Thunderclap</p><small class="preview-label">Emerald Park · Practice adventure</small></section>
<div id="message" role="status" aria-live="polite"></div><div id="countdown" aria-live="assertive"></div>
<div id="controls" hidden><div class="steering"><button id="left" aria-label="Steer left">◀</button><button id="right" aria-label="Steer right">▶</button></div><div class="actions"><button id="clap">Clap<small>65 power · C</small></button><button id="smash">Smash<small>25 power · X</small></button><button id="jump" class="jump">Jump<small>Space</small></button></div></div>
<section id="pause-panel" class="panel modal" hidden><span class="eyebrow">TAKE A BREATHER</span><h2>Ready, hero?</h2><button id="resume" class="primary">Keep running</button><button id="restart-pause">Start again</button><label class="check"><input type="checkbox" id="reduced"> Reduce background motion</label><button id="back-home">Back to park</button></section>
<section id="results" class="panel modal" hidden><span class="eyebrow">EMERALD PARK</span><h2>Great run, Jamesy!</h2><div id="results-score"></div><p id="results-detail"></p><button id="retry" class="primary">Run again</button><button id="results-art">Explore the art</button><small>Practice mode · Scores reset for each run.</small></section>
<section id="library" hidden><div class="library-heading"><div><span class="eyebrow">THE EMERALD COLLECTION</span><h2>Art in motion</h2><p>Six animations · Ten illustrated assets</p></div><button id="close-library">Back to game</button></div><div class="review-controls"><button id="play-motion">Pause animation</button><label>Speed <select id="motion-speed"><option value=".25">¼ speed</option><option value=".5">½ speed</option><option value="1" selected>Normal</option><option value="2">2× speed</option></select></label><label>Background <select id="review-background"><option value="park">Park green</option><option value="dark">Dark</option><option value="light">Light</option><option value="checker">Checkerboard</option></select></label></div><div id="motion-cards" class="cards"></div><h3>Detailed source designs</h3><div id="source-cards" class="cards sources"></div><p class="review-note">Explore the treasures, obstacles, and scenery that bring Emerald Park to life.</p></section>`;
const $=id=>document.getElementById(id),settings={quality:'high',music:0,sfx:0,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches};
let engine,art,motionRunning=true,motionTime=0,lastMotion=0,reviewWasRunning=false,messageTimeout,motionCards=[];
const audio=new AudioEngine(settings),keys=new Set(),touch=new Set();
function steer(){engine?.steerTo((keys.has('right')||touch.has('right')?1:0)-(keys.has('left')||touch.has('left')?1:0));}
function clearInput(){keys.clear();touch.clear();engine?.steerTo(0);}
function message(text){$('message').textContent=text;clearTimeout(messageTimeout);messageTimeout=setTimeout(()=>$('message').textContent='',2400);}
function hud(run,level){$('gems').textContent=run.gems;$('stars').textContent=run.specials;$('score').textContent=run.score.toLocaleString()+' points';$('power-label').textContent=Math.round(run.power)+'%';$('power-fill').style.width=run.power+'%';$('distance-fill').style.width=Math.min(100,run.distance/level.length*100)+'%';$('smash').disabled=run.power<25||run.smashTimer>0;$('clap').disabled=run.power<65||run.clapTimer>0;}
function start(){clearInput();for(const id of['welcome','pause-panel','results','library'])$(id).hidden=true;for(const id of['hud','controls','pause'])$(id).hidden=false;void audio.unlock();engine.start(0,'cozy');$('start').blur();}
function paused(){clearInput();$('pause-panel').hidden=false;$('pause').textContent='Resume';}
function resume(){$('pause-panel').hidden=true;engine.resume();$('pause').textContent='Pause';}
function finish(run){clearInput();$('controls').hidden=true;$('pause').hidden=true;$('results').hidden=false;$('results-score').textContent=run.score.toLocaleString()+' points';$('results-detail').textContent=`${run.gems} gems · ${run.specials} stars · ${run.smashes} obstacles smashed`;}
function openLibrary(){reviewWasRunning=['running','countdown'].includes(engine.state);engine.pause();$('pause-panel').hidden=true;$('library').hidden=false;$('close-library').focus();}
function closeLibrary(){$('library').hidden=true;if(reviewWasRunning)resume();else if(engine.state==='paused')$('pause-panel').hidden=false;$('library-button').focus();}
function buildReview(){
 $('motion-cards').innerHTML=art.data.clips.map((c,i)=>`<article class="motion-card"><div class="motion-stage" data-background="park"><canvas width="512" height="512" id="motion-${i}" aria-label="${c.id} animation"></canvas></div><div class="card-copy"><span class="eyebrow">${c.loop?'LOOP':'SMASH REACTION'}</span><h3>${art.data.assets.find(a=>a.id===c.asset).label}</h3><p>${c.frames.length} drawings · ${c.fps} frames/sec</p><div class="frame-control"><button data-replay="${i}">${c.loop?'Restart':'Smash rock'}</button><label>Frame <input data-frame="${i}" type="range" min="0" max="${c.sequence.length-1}" value="0" aria-label="${c.id} frame"></label><output id="frame-${i}">1</output></div><small>${c.note}</small></div></article>`).join('');
 $('source-cards').innerHTML=art.data.assets.map(a=>`<article><div class="source-stage" data-background="park"><img loading="lazy" src="${assetURL(a.file)}" alt="${a.label}"></div><h3>${a.label}</h3><p>${a.sourceSize.join(' × ')} original · ${a.anchor==='ground'?'Ground anchor':'Center anchor'}</p></article>`).join('');
 motionCards=art.data.clips.map((clip,i)=>{const img=new Image();img.src=assetURL(clip.file);return{clip,img,canvas:$('motion-'+i),start:0,manual:null};});
 document.querySelectorAll('[data-replay]').forEach(b=>b.onclick=()=>{const c=motionCards[+b.dataset.replay];c.start=motionTime;c.manual=null;});
 document.querySelectorAll('[data-frame]').forEach(input=>input.oninput=()=>{motionCards[+input.dataset.frame].manual=+input.value;});
 requestAnimationFrame(drawReview);
}
function drawReview(now){const dt=lastMotion?Math.min(.05,(now-lastMotion)/1000):0;lastMotion=now;if(motionRunning&&!$('library').hidden)motionTime+=dt*Number($('motion-speed').value);
 if(!$('library').hidden)motionCards.forEach((c,i)=>{let index=c.manual??Math.floor((motionTime-c.start)*c.clip.fps);index=c.clip.loop?index%c.clip.sequence.length:Math.min(index,c.clip.sequence.length-1);const frame=c.clip.frames[c.clip.sequence[index]],ctx=c.canvas.getContext('2d');ctx.clearRect(0,0,512,512);if(c.img.complete&&c.img.naturalWidth){ctx.drawImage(c.img,...frame.rect,0,0,512,512);}$('frame-'+i).textContent=String(index+1);if(c.manual===null)document.querySelector(`[data-frame="${i}"]`).value=index;});requestAnimationFrame(drawReview);
}
$('play-motion').onclick=()=>{motionRunning=!motionRunning;$('play-motion').textContent=motionRunning?'Pause animation':'Play animation';if(motionRunning)motionCards.forEach(c=>c.manual=null);};
$('review-background').onchange=e=>document.querySelectorAll('[data-background]').forEach(el=>el.dataset.background=e.target.value);
$('sound').onclick=()=>{const on=settings.sfx===0;settings.music=on?.5:0;settings.sfx=on?.6:0;$('sound').textContent=on?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(on));$('sound').setAttribute('aria-label',on?'Mute sound':'Enable sound');void audio.unlock();};
$('reduced').checked=settings.reduced;$('reduced').onchange=e=>settings.reduced=e.target.checked;
for(const id of['start','retry','restart-pause'])$(id).onclick=()=>engine&&start();
$('resume').onclick=resume;$('pause').onclick=()=>engine.state==='paused'?resume():engine.pause();
$('back-home').onclick=()=>{clearInput();engine.menu(0);$('welcome').hidden=false;for(const id of['hud','controls','pause-panel','pause','results'])$(id).hidden=true;};
for(const id of['library-button','results-art'])$(id).onclick=()=>engine&&openLibrary();$('close-library').onclick=closeLibrary;
for(const id of['jump','smash','clap'])$(id).onclick=()=>engine?.[id]();
for(const id of['left','right']){$(id).onpointerdown=e=>{e.preventDefault();$(id).setPointerCapture(e.pointerId);touch.add(id);steer();};const release=()=>{touch.delete(id);steer();};$(id).onpointerup=release;$(id).onpointercancel=release;$(id).onlostpointercapture=release;}
document.addEventListener('keydown',e=>{if(!engine||!$('library').hidden||/INPUT|SELECT/.test(e.target.tagName))return;const key=e.key.toLowerCase();if(['arrowleft','arrowright','a','d',' ','x','c','escape'].includes(key))e.preventDefault();if(['arrowleft','a'].includes(key))keys.add('left');if(['arrowright','d'].includes(key))keys.add('right');steer();if(e.repeat)return;if(key===' ')engine.jump();if(key==='x')engine.smash();if(key==='c')engine.clap();if(key==='escape')engine.state==='paused'?resume():engine.pause();});
document.addEventListener('keyup',e=>{const key=e.key.toLowerCase();if(['arrowleft','a'].includes(key))keys.delete('left');if(['arrowright','d'].includes(key))keys.delete('right');steer();});
window.addEventListener('blur',()=>{clearInput();engine?.pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();engine?.pause();}});
try{art=await loadArt();engine=new EmeraldPreview($('game'),settings,audio,{hud,message,countdown:n=>$('countdown').textContent=n||'',paused,finish,error:message},art);buildReview();$('start').disabled=false;$('start').textContent='Let’s play';if(new URLSearchParams(location.search).has('qa'))window.__jamesyPreview={engine,art,settings};}
catch(error){console.error(error);$('start').textContent='Could not open the park';message('The park could not load. Please reopen it in a browser with WebGL enabled.');}
