import {chromium} from 'playwright';import sharp from 'sharp';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdir,writeFile,readFile} from 'node:fs/promises';
const root='http://127.0.0.1:4173/James-Hulk-Racer/',server=spawn(process.execPath,['scripts/serve.mjs'],{stdio:'inherit'});let browser;const checks=[],errors=[];const ok=s=>{checks.push(s);console.log('PASS',s);};
await mkdir('dist/assets',{recursive:true});await mkdir('dist/qa',{recursive:true});
try{
 for(let i=0;i<50;i++){try{if((await fetch(root)).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1280,height:800},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 for(const name of['park','cavern','volcano','portrait','share']){
  await page.setViewportSize(name==='portrait'?{width:768,height:768}:name==='share'?{width:1200,height:630}:{width:1280,height:720});await page.goto(root+'?capture='+name);await page.waitForFunction(()=>window.__jamesReady,{},{timeout:45000});await page.waitForTimeout(1400);const buffer=await page.screenshot();const stats=await sharp(buffer).stats();assert.ok(stats.channels.some(c=>c.stdev>15),'3D render must not be blank');
  if(name==='portrait'){await sharp(buffer).resize(512,512).webp({quality:86}).toFile('dist/assets/portrait.webp');for(const size of[180,192,512])await sharp(buffer).resize(size,size).png().toFile(`dist/assets/icon-${size}.png`);}
  else if(name==='share'){const overlay=Buffer.from('<svg width="1200" height="630"><defs><linearGradient id="g"><stop stop-color="#102d29" stop-opacity=".97"/><stop offset="1" stop-color="#102d29" stop-opacity="0"/></linearGradient></defs><rect width="730" height="630" fill="url(#g)"/><text x="70" y="190" fill="#d7f5c0" font-family="sans-serif" font-weight="bold" font-size="23" letter-spacing="4">JAMES GAME CENTER</text><text x="65" y="290" fill="white" font-family="sans-serif" font-weight="900" font-size="57">JAMESY THE</text><text x="60" y="405" fill="#b9f57a" font-family="sans-serif" font-weight="900" font-size="105">HULK RACER</text><text x="70" y="475" fill="#e1eedc" font-family="sans-serif" font-size="25">Little hero. Big adventure.</text></svg>');await sharp(buffer).composite([{input:overlay}]).jpeg({quality:88}).toFile('dist/assets/share.jpg');}
  else await sharp(buffer).resize(960,540).webp({quality:82}).toFile(`dist/assets/${name}.webp`);
  ok(`${name}: real WebGL scene rendered`);
 }
 await page.setViewportSize({width:1440,height:1000});await page.goto(root);await page.waitForFunction(()=>window.__jamesReady);await page.waitForTimeout(500);assert.equal(await page.locator('[data-level]').count(),3);await page.screenshot({path:'dist/qa/desktop-menu.png'});ok('Desktop menu and three world selectors');
 await page.locator('[data-dialog="profile"]').click();await page.locator('#nickname').fill('Hero James');await page.locator('#nickname-form button').click();await page.locator('#profile-dialog [data-close]').click();assert.equal(await page.locator('.profile-btn [data-name]').textContent(),'Hero James');ok('Nickname saves safely');
 await page.locator('#play').click();await page.waitForFunction(()=>window.__race.state==='running');await page.keyboard.down('ArrowRight');await page.waitForTimeout(350);await page.keyboard.up('ArrowRight');assert.ok(await page.evaluate(()=>window.__race.theta>.15));await page.locator('#jump').dispatchEvent('pointerdown');assert.ok(await page.evaluate(()=>window.__race.run.jumpTime>0));ok('Desktop steering and jump');
 await page.locator('#pause').click();const distance=await page.evaluate(()=>window.__race.run.distance);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.__race.run.distance),distance);await page.locator('#resume').click();ok('Pause freezes progress and resumes');
 await page.evaluate(()=>{const e=window.__race;e.run.power=65;e.run.smashTimer=0;e.run.clapTimer=0;e.smash();e.clap();});assert.ok(await page.evaluate(()=>window.__race.run.smashTimer>0&&window.__race.run.clapTimer>0));await page.evaluate(()=>{const e=window.__race;e.run.power=100;e.tick(.016);});assert.ok(await page.evaluate(()=>window.__race.run.burst>0));ok('Smash, thunderclap and full-power burst');
 await page.screenshot({path:'dist/qa/desktop-race.png'});await page.evaluate(()=>{const e=window.__race;e.run.distance=e.level.length-.05;e.tick(.05);});await page.waitForSelector('#results-dialog[open]');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('james-center:profile:v1')).runs),1);await page.screenshot({path:'dist/qa/results.png'});ok('Finish records progress once and displays results');await page.locator('#result-menu').click();
 await page.locator('[data-mode="hero"]').click();await page.locator('#play').click();await page.waitForFunction(()=>window.__race.state==='running');await page.evaluate(()=>{const e=window.__race;e.theta=e.targetTheta=0;e.run.jump=e.run.jumpTime=e.run.invulnerable=e.run.power=0;e.run.hearts=1;e.course=[{s:e.run.distance+1,theta:0,lane:2,kind:'rock',done:false}];e.tick(.016);});await page.waitForSelector('#results-dialog[open]');assert.equal(await page.locator('#result-title').textContent(),'You’ve got this!');ok('Superhero three-shield game-over');await context.close();
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});const phone=await mobile.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto(root);await phone.waitForFunction(()=>window.__jamesReady);assert.ok(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await phone.screenshot({path:'dist/qa/phone-menu.png'});await phone.locator('#play').click();await phone.waitForFunction(()=>window.__race.state==='running');const bounds=await phone.locator('[data-steer="1"]').boundingBox();await phone.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);await phone.mouse.down();await phone.waitForTimeout(350);await phone.mouse.up();assert.ok(await phone.evaluate(()=>window.__race.theta>.15));await phone.screenshot({path:'dist/qa/phone-race.png'});ok('390px mobile layout and on-screen steering');await phone.setViewportSize({width:844,height:390});await phone.waitForTimeout(600);const controls=await phone.locator('#controls').boundingBox();assert.ok(controls.x>=0&&controls.y+controls.height<=391);await phone.screenshot({path:'dist/qa/landscape-race.png'});ok('Mobile landscape controls remain inside viewport');
 assert.deepEqual(errors,[],'No uncaught browser errors');ok('No uncaught browser errors');
 const report={result:'PASS',browser:'Chromium with software WebGL; mobile viewport simulation, not a physical iPhone/Safari test',checks,errors};await writeFile('dist/qa/report.json',JSON.stringify(report,null,2));await writeFile('dist/qa/index.html','<!doctype html><html><meta name="viewport" content="width=device-width"><title>Jamesy: actual build previews</title><style>body{background:#102d29;color:#f3f6e9;font:16px system-ui;max-width:1100px;margin:30px auto;padding:20px}img{max-width:100%;border-radius:16px;margin:15px 0}h1{font-size:30px}a{color:#c4ff97}</style><h1>Actual game build previews</h1><p>Rendered from the playable Three.js game. These are not the AI concept illustrations.</p><p><a href="report.json">Browser test report</a></p>'+['desktop-menu','desktop-race','phone-menu','phone-race','landscape-race','results'].map(n=>`<h2>${n.replaceAll('-',' ')}</h2><img src="${n}.png" alt="${n}">`).join('')+'</html>');
}catch(e){await writeFile('dist/qa/report.json',JSON.stringify({result:'FAIL',checks,errors,error:e.stack},null,2));console.error(e);process.exitCode=1;}finally{await browser?.close();server.kill();}
