import './shared/style.css';
import './racer.css';
import {LEVELS,clamp,bits,powerStage} from './game/logic.js';
import {AudioEngine} from './game/audio.js';
import {profile,settings,saveSettings,record} from './shared/profile.js';
import {header,icon,installDialogs,toast,HUB} from './shared/ui.js';
const $=s=>document.querySelector(s),app=$('#app');let selected=profile.lastLevel,engine,dialogs,roundRecorded=false;
const query=new URLSearchParams(location.search);const requested=Number(query.get('level'));if(query.has('level')&&Number.isInteger(requested))selected=clamp(requested,0,2);
app.innerHTML=`<canvas id="scene" aria-label="Jamesy's interactive three-dimensional racing world"></canvas>${header('Hulk Racer')}
<main id="menu" class="race-menu"><div class="menu-inner"><section class="race-intro"><span class="eyebrow"><i class="live-dot"></i> LITTLE HERO. BIG ADVENTURE.</span><h1><span>JAMESY THE</span><strong>HULK</strong> RACER</h1><p>Race the half-pipe. Collect your power.<br>Unleash your inner superhero.</p><div class="mode-toggle" aria-label="Difficulty"><button data-mode="cozy"><span>Little Hero</span><small>Gentle pace · keep going</small></button><button data-mode="hero"><span>Superhero</span><small>Faster · 3 shields</small></button></div><button id="play" class="btn play-btn" disabled>${icon('play')}<span>Loading powers…</span>${icon('right')}</button><div class="intro-links"><button class="text-btn" data-dialog="help">${icon('help')} How to play</button><button class="text-btn" data-dialog="trophies">${icon('trophy')} Trophy room</button></div></section><div class="hero-caption" aria-hidden="true"><span>MEET YOUR HERO</span><strong>Jamesy</strong><small>Strong. Brave. Ready for anything.</small></div>
<section class="world-section" aria-labelledby="world-heading"><div class="section-heading"><h2 id="world-heading">Choose your adventure</h2><span>3 worlds. One super you.</span></div><div class="world-grid">${LEVELS.map((l,i)=>`<button class="world-card ${l.id}" data-level="${i}" aria-pressed="false"><div class="world-art"><img src="./assets/${l.id}.webp" alt="" loading="lazy" onerror="this.style.visibility='hidden'"><span class="world-number">0${i+1}</span><span class="world-medals" data-world-medals="${i}"></span></div><div class="world-info"><strong>${l.name}</strong><span>${l.tag}</span><small data-best="${i}"></small></div>${icon('check','world-check')}</button>`).join('')}</div></section></div></main>
<section id="hud" hidden aria-label="Race information"><div class="hud-top"><div class="hud-score"><span class="hud-avatar">J</span><div><small id="race-name"></small><strong id="score">0</strong></div></div><div class="hud-treasures">${icon('gem')}<strong id="treasures">0</strong></div><div class="hud-power"><label id="power-label" for="power-meter">POWER UP</label><div class="meter-wrap">${icon('bolt')}<progress id="power-meter" max="100" value="0"></progress><span id="power-value">0%</span></div></div><button id="pause" class="icon-btn" aria-label="Pause game">${icon('pause')}</button></div><div class="hud-bottom"><span id="world-name"></span><span id="shields"></span></div><progress id="distance-meter" max="100" value="0" aria-label="Level progress"></progress></section>
<div id="countdown" hidden aria-live="polite"></div><div id="race-message" role="status"></div>
<section id="controls" hidden aria-label="Game controls"><div class="steering"><button class="game-button steer-button" data-steer="-1" aria-label="Steer left">${icon('left')}</button><button class="game-button steer-button" data-steer="1" aria-label="Steer right">${icon('right')}</button></div><div class="power-controls"><button class="game-button" id="jump">${icon('jump')}<span>JUMP</span></button><button class="game-button smash" id="smash">${icon('bolt')}<span>SMASH</span><small id="smash-status">25 POWER</small></button><button class="game-button clap" id="clap">${icon('sun')}<span>CLAP</span><small id="clap-status">65 POWER</small></button></div></section>
<dialog id="pause-dialog" class="panel-dialog compact"><span class="eyebrow">TAKE A HERO BREAK</span><h2>Adventure paused</h2><p>Your world will be right here.</p><button class="btn" id="resume">${icon('play')} Keep going</button><button class="btn secondary" id="pause-settings">${icon('settings')} Sound & settings</button><button class="text-btn" id="quit">Back to adventures</button></dialog>
<dialog id="results-dialog" class="panel-dialog results"><span class="eyebrow" id="result-eyebrow">ADVENTURE COMPLETE</span><div id="result-stars"></div><h2 id="result-title"></h2><p id="result-world"></p><strong id="result-score"></strong><span class="score-caption">HERO POINTS</span><div class="stats-grid"><div><strong id="result-treasures"></strong><span>Treasures</span></div><div><strong id="result-smashes"></strong><span>Smashes</span></div><div><strong id="result-combo"></strong><span>Best combo</span></div></div><p id="medal-description" class="small-note"></p><button class="btn" id="next-world">Next adventure ${icon('right')}</button><button class="btn secondary" id="replay">${icon('play')} Race again</button><button class="text-btn" id="result-menu">Choose a world</button></dialog>
<div id="load-error" class="error-panel" hidden><h2>One more moment, hero.</h2><p></p><button class="btn" onclick="location.reload()">Try again</button><a class="btn secondary" href="${HUB}">Game Center</a></div><footer class="race-footer">Created by Sean <span>·</span> A James Game Center adventure</footer>`;
const audio=new AudioEngine(settings);let messageTimer;
function message(text,quiet=false){const el=$('#race-message');el.textContent=text;el.classList.toggle('quiet',quiet);el.classList.add('visible');clearTimeout(messageTimer);messageTimer=setTimeout(()=>el.classList.remove('visible'),quiet?1800:2400);}
function updateSelection(){document.querySelectorAll('[data-level]').forEach(b=>{const on=Number(b.dataset.level)===selected;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on);});document.querySelectorAll('[data-mode]').forEach(b=>{const on=b.dataset.mode===settings.mode;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',on);});document.querySelectorAll('[data-world-medals]').forEach(el=>{const m=profile.medals[Number(el.dataset.worldMedals)];el.innerHTML=[1,2,4].map(n=>icon('star',m&n?'earned':'')).join('');});document.querySelectorAll('[data-best]').forEach(el=>{const score=profile[settings.mode==='cozy'?'bestCozy':'bestHero'][Number(el.dataset.best)];el.textContent=score?`BEST ${score.toLocaleString()}`:'READY TO EXPLORE';});if(engine)$('#play span').textContent='Let’s race!';}
function showRace(on){document.body.classList.toggle('in-race',on);$('#menu').hidden=on;$('#hud').hidden=!on;$('#controls').hidden=!on;$('.site-header').hidden=on;$('.race-footer').hidden=on;}
async function start(index=selected){if(!engine)return;selected=index;roundRecorded=false;document.querySelectorAll('dialog[open]').forEach(d=>d.close());showRace(true);$('#countdown').hidden=false;$('#countdown').textContent='3';$('#race-name').textContent=profile.name.toUpperCase();await audio.unlock();engine.start(selected,settings.mode);}
function goMenu(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());engine?.menu(selected);showRace(false);$('#countdown').hidden=true;$('#race-message').classList.remove('visible');updateSelection();}
function onFinish(result,level){if(!roundRecorded){record(result,selected);roundRecorded=true;}$('#controls').hidden=true;$('#result-eyebrow').textContent=result.complete?'ADVENTURE COMPLETE':'EVERY HERO KEEPS TRYING';$('#result-title').textContent=result.complete?(result.bursts?'Super Jamesy!':'You did it, hero!'):'You’ve got this!';$('#result-world').textContent=level.name;$('#result-score').textContent=result.score.toLocaleString();$('#result-treasures').textContent=result.collected;$('#result-smashes').textContent=result.smashes;$('#result-combo').textContent=result.maxCombo;$('#result-stars').innerHTML=[1,2,4].map(n=>icon('star',result.medals&n?'earned':'')).join('');$('#medal-description').textContent=result.complete?`${bits(result.medals)} medals this run · Finish, collect half the treasures, and avoid every bump to earn all three.`:'Try Little Hero mode for a gentler pace with no game-over.';$('#next-world').hidden=!result.complete;$('#next-world').innerHTML=(selected===2?'Back to adventures':'Next adventure')+icon('right');$('#results-dialog').showModal();}
function onHud(r,l){$('#score').textContent=r.score.toLocaleString();$('#treasures').textContent=r.collected;$('#power-meter').value=r.power;$('#power-value').textContent=`${Math.floor(r.power)}%`;$('#power-label').textContent=['POWER UP','SPARKING','SMASH READY','SUPER CHARGED','SUPER JAMESY!'][powerStage(r.power,r.burst>0)];$('#distance-meter').value=Math.min(100,r.distance/l.length*100);$('#world-name').textContent=l.name;$('#shields').textContent=r.mode==='cozy'?'LITTLE HERO':'◆'.repeat(r.hearts)+'◇'.repeat(3-r.hearts);for(const[k,threshold]of[['smash',25],['clap',65]]){const cooldown=k==='smash'?r.smashTimer:r.clapTimer,ready=(r.power>=threshold||r.burst>0)&&cooldown<=0;$('#'+k).classList.toggle('ready',ready);$('#'+k).setAttribute('aria-disabled',String(!ready));$('#'+k+'-status').textContent=cooldown>0?`${Math.ceil(cooldown)}s`:ready?'READY':`${threshold} POWER`;}}
function updateSettings(){if(!engine)return;engine.renderer.setPixelRatio(Math.min(devicePixelRatio||1,settings.quality==='low'?1:settings.quality==='high'?2:1.5));engine.renderer.shadowMap.enabled=settings.quality==='high'||(settings.quality==='auto'&&innerWidth>1000);engine.resize();document.body.classList.toggle('gentle-effects',settings.reduced);}
dialogs=installDialogs(updateSettings,()=>engine?.pause());
$('#play').onclick=()=>start();$('#pause').onclick=()=>engine?.pause();$('#resume').onclick=async()=>{$('#pause-dialog').close();await audio.unlock();engine?.resume();};$('#pause-settings').onclick=()=>dialogs.open('settings');$('#quit').onclick=goMenu;$('#replay').onclick=()=>start();$('#result-menu').onclick=goMenu;$('#next-world').onclick=()=>selected===2?goMenu():start(selected+1);
$('#pause-dialog').addEventListener('cancel',e=>{e.preventDefault();$('#resume').click();});$('#results-dialog').addEventListener('cancel',e=>{e.preventDefault();goMenu();});
for(const action of['jump','smash','clap'])$('#'+action).addEventListener('pointerdown',e=>{e.preventDefault();engine?.[action]();});
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.level);engine?.menu(selected);updateSelection();});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{settings.mode=b.dataset.mode;saveSettings();updateSelection();});
const held=new Map(),keys=new Set();function steering(){engine?.steerTo(clamp([...held.values()].reduce((a,b)=>a+b,0)+(keys.has('ArrowRight')||keys.has('KeyD')?1:0)-(keys.has('ArrowLeft')||keys.has('KeyA')?1:0),-1,1));}
document.querySelectorAll('[data-steer]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held.set(e.pointerId,Number(b.dataset.steer));steering();});for(const event of['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,e=>{held.delete(e.pointerId);steering();});});
let swipe=null;$('#scene').addEventListener('pointerdown',e=>{if(engine?.state!=='running')return;swipe={x:e.clientX,y:e.clientY,theta:engine.targetTheta,id:e.pointerId};e.target.setPointerCapture(e.pointerId);});$('#scene').addEventListener('pointermove',e=>{if(!swipe||e.pointerId!==swipe.id)return;const dx=e.clientX-swipe.x,dy=e.clientY-swipe.y;engine.targetTheta=clamp(swipe.theta+dx/Math.max(160,innerWidth*.38),-1.05,1.05);if(dy< -55){engine.jump();swipe.y=e.clientY;}});for(const ev of['pointerup','pointercancel'])$('#scene').addEventListener(ev,()=>swipe=null);
window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||document.querySelector('dialog[open]'))return;if(e.code==='Escape'){engine?.pause();return;}if(engine?.state!=='running')return;if(['ArrowLeft','ArrowRight','KeyA','KeyD','Space','KeyS','KeyC'].includes(e.code))e.preventDefault();keys.add(e.code);steering();if(!e.repeat){if(e.code==='Space')engine.jump();if(e.code==='KeyS')engine.smash();if(e.code==='KeyC')engine.clap();}});window.addEventListener('keyup',e=>{keys.delete(e.code);steering();});
function blur(){keys.clear();held.clear();swipe=null;steering();engine?.pause();}window.addEventListener('blur',blur);document.addEventListener('visibilitychange',()=>{if(document.hidden)blur();});window.addEventListener('james-profile',updateSelection);
function error(text){$('#load-error').hidden=false;$('#load-error p').textContent=text;$('#play').disabled=true;console.error(text);}
updateSelection();
try{const {RaceEngine}=await import('./game/engine.js');engine=new RaceEngine($('#scene'),settings,audio,{hud:onHud,message,finish:onFinish,countdown:n=>{if(n>0){$('#countdown').textContent=n;$('#countdown').hidden=false;}else{$('#countdown').hidden=true;}},paused:()=>{if(!$('#pause-dialog').open)$('#pause-dialog').showModal();},error});engine.menu(selected);updateSettings();$('#play').disabled=false;updateSelection();window.__jamesReady=true;if(query.has('capture')){document.body.classList.add('capture');engine.capture(query.get('capture'));}if(['localhost','127.0.0.1'].includes(location.hostname))window.__race=engine;}catch(e){error('The 3D game could not start. Try reloading in an updated Safari, Chrome or Edge browser with WebGL enabled. Your saved progress has not been removed.');console.error(e);}
if('serviceWorker' in navigator&&!query.has('capture'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{}));
